version: "3"
services:
  mongo:
    image: mongo:3.4.23
    ports:
      - "27017:27017"
    volumes:
      - mongo_service_volume:/data/db

  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blueprint_roa_golang
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  simple_jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
volumes:
  mongo_service_volume:
    driver: local
  postgres-data: