// Code generated by "stringer -type ErrorCode internals/constants/error_code.go"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTERNAL-1]
	_ = x[BAD_REQUEST-2]
}

const _ErrorCode_name = "INTERNALBAD_REQUEST"

var _ErrorCode_index = [...]uint8{0, 8, 19}

func (i ErrorCode) String() string {
	i -= 1
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
