// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	utils "github.com/robowealth-mutual-fund/blueprint-roa-golang/internals/utils"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Begin provides a mock function with given fields:
func (_m *Repository) Begin() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Commit provides a mock function with given fields: db
func (_m *Repository) Commit(db *gorm.DB) *gorm.DB {
	ret := _m.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Create provides a mock function with given fields: ent
func (_m *Repository) Create(ent interface{}) error {
	ret := _m.Called(ent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: db, ent
func (_m *Repository) CreateTransaction(db *gorm.DB, ent interface{}) error {
	ret := _m.Called(db, ent)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, interface{}) error); ok {
		r0 = rf(db, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: filters, ent
func (_m *Repository) Find(filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}) error); ok {
		r0 = rf(filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// First provides a mock function with given fields: filters, ent
func (_m *Repository) First(filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}) error); ok {
		r0 = rf(filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsErrorRecordNotFound provides a mock function with given fields: err
func (_m *Repository) IsErrorRecordNotFound(err error) bool {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsErrorRecordNotFound")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(error) bool); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Last provides a mock function with given fields: filters, ent
func (_m *Repository) Last(filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for Last")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}) error); ok {
		r0 = rf(filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: tableName, offset, limit, filters, order, ent
func (_m *Repository) List(tableName string, offset int64, limit int64, filters interface{}, order interface{}, ent interface{}) (*utils.Pagination, error) {
	ret := _m.Called(tableName, offset, limit, filters, order, ent)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *utils.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, int64, interface{}, interface{}, interface{}) (*utils.Pagination, error)); ok {
		return rf(tableName, offset, limit, filters, order, ent)
	}
	if rf, ok := ret.Get(0).(func(string, int64, int64, interface{}, interface{}, interface{}) *utils.Pagination); ok {
		r0 = rf(tableName, offset, limit, filters, order, ent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, int64, interface{}, interface{}, interface{}) error); ok {
		r1 = rf(tableName, offset, limit, filters, order, ent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Raw provides a mock function with given fields: ent, sql, value
func (_m *Repository) Raw(ent interface{}, sql string, value ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ent, sql)
	_ca = append(_ca, value...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Raw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = rf(ent, sql, value...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with given fields: db
func (_m *Repository) Rollback(db *gorm.DB) *gorm.DB {
	ret := _m.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = rf(db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// RollbackTo provides a mock function with given fields: db, input
func (_m *Repository) RollbackTo(db *gorm.DB, input string) *gorm.DB {
	ret := _m.Called(db, input)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTo")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *gorm.DB); ok {
		r0 = rf(db, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// SavePoint provides a mock function with given fields: db, input
func (_m *Repository) SavePoint(db *gorm.DB, input string) *gorm.DB {
	ret := _m.Called(db, input)

	if len(ret) == 0 {
		panic("no return value specified for SavePoint")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *gorm.DB); ok {
		r0 = rf(db, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Update provides a mock function with given fields: filters, ent
func (_m *Repository) Update(filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}) error); ok {
		r0 = rf(filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransaction provides a mock function with given fields: db, filters, ent
func (_m *Repository) UpdateTransaction(db *gorm.DB, filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(db, filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, map[string]interface{}, interface{}) error); ok {
		r0 = rf(db, filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: tableName, filters, ent
func (_m *Repository) Upsert(tableName string, filters map[string]interface{}, ent interface{}) error {
	ret := _m.Called(tableName, filters, ent)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}, interface{}) error); ok {
		r0 = rf(tableName, filters, ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
