// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ent
func (_m *Repository) Create(ent interface{}) error {
	ret := _m.Called(ent)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(ent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: filters, order, out
func (_m *Repository) List(filters map[string]interface{}, order interface{}, out interface{}) error {
	ret := _m.Called(filters, order, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, interface{}, interface{}) error); ok {
		r0 = rf(filters, order, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
